# Generated by Django 6.1.1 on 2026-10-02 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('state', models.CharField(choices=[('abia', 'ABIA'), ('adamawa', 'ADAMAWA'), ('akwa-ibom', 'AKWA-IBOM'), ('anambra', 'ANAMBRA'), ('bauchi', 'BAUCHI'), ('bayelsa', 'BAYELSA'), ('benue', 'BENUE'), ('borno', 'BORNO'), ('cross-river', 'CROSS-RIVER'), ('delta', 'DELTA'), ('ebonyi', 'EBONYI'), ('edo', 'EDO'), ('ekiti', 'EKITI'), ('enugu', 'ENUGU'), ('gombe', 'GOMBE'), ('imo', 'IMO'), ('jigawa', 'JIGAWA'), ('kaduna', 'KADUNA'), ('kano', 'KANO'), ('katsina', 'KATSINA'), ('kebbi', 'KEBBI'), ('kogi', 'KOGI'), ('kwara', 'KWARA'), ('lagos', 'LAGOS'), ('nasarawa', 'NASARAWA'), ('niger', 'NIGER'), ('ogun', 'OGUN'), ('ondo', 'ONDO'), ('osun', 'OSUN'), ('oyo', 'OYO'), ('plateau', 'PLATEAU'), ('rivers', 'RIVERS'), ('sokoto', 'SOKOTO'), ('taraba', 'TARABA'), ('yobe', 'YOBE'), ('zamfara', 'ZAMFARA'), ('abuja', 'ABUJA')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=11)),
                ('matric_no', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('100', '100 LEVEL'), ('200', '200 LEVEL'), ('300', '300 LEVEL'), ('400', '400 LEVEL'), ('500', '500 LEVEL')], max_length=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='supervision.department')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='supervision.supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9)),
                ('on_site_days', models.JSONField(default=list)),
                ('on_site_start', models.TimeField()),
                ('on_site_end', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='students.enterprise')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
