# Generated by Django 6.1.1 on 2026-10-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='visit_status',
            field=models.CharField(choices=[('VISITED', 'Visited'), ('NOT_VISITED', 'Not visited')], default='NOT_VISITED', max_length=20),
        ),
    ]
