# Generated by Django 6.1.1 on 2026-10-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        ('students', '0002_placement_planned_date_placement_visit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='enterprises.enterprise'),
        ),
        migrations.DeleteModel(
            name='Enterprise',
        ),
    ]
