# Generated by Django 6.1.1 on 2026-10-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_placement_enterprise_delete_enterprise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='on_site_end',
            new_name='closing_time',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='on_site_start',
            new_name='resumption_time',
        ),
    ]
