# Generated by Django 6.1.1 on 2026-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_on_site_end_placement_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='on_site_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='resumption_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
