# Generated by Django 6.1.1 on 2026-10-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '__first__'),
        ('students', '0005_alter_placement_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='departments.department'),
        ),
    ]
