# Generated by Django 6.1.1 on 2026-10-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0002_remove_department_code_name_remove_department_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='title',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('ADMIN', 'Department Admin'), ('SIWES_COORDINATOR', 'SIWES Coordinator')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
