# Generated by Django 6.1.1 on 2026-10-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '__first__'),
        ('students', '0006_alter_student_department'),
        ('supervision', '0003_departmentstaff_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentstaff',
            name='department',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='departments.department'),
        ),
        migrations.RemoveField(
            model_name='departmentstaff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DepartmentStaff',
        ),
    ]
