# Generated by Django 6.1.1 on 2026-10-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('state', models.CharField(choices=[('abia', 'ABIA'), ('adamawa', 'ADAMAWA'), ('akwa-ibom', 'AKWA-IBOM'), ('anambra', 'ANAMBRA'), ('bauchi', 'BAUCHI'), ('bayelsa', 'BAYELSA'), ('benue', 'BENUE'), ('borno', 'BORNO'), ('cross-river', 'CROSS-RIVER'), ('delta', 'DELTA'), ('ebonyi', 'EBONYI'), ('edo', 'EDO'), ('ekiti', 'EKITI'), ('enugu', 'ENUGU'), ('gombe', 'GOMBE'), ('imo', 'IMO'), ('jigawa', 'JIGAWA'), ('kaduna', 'KADUNA'), ('kano', 'KANO'), ('katsina', 'KATSINA'), ('kebbi', 'KEBBI'), ('kogi', 'KOGI'), ('kwara', 'KWARA'), ('lagos', 'LAGOS'), ('nasarawa', 'NASARAWA'), ('niger', 'NIGER'), ('ogun', 'OGUN'), ('ondo', 'ONDO'), ('osun', 'OSUN'), ('oyo', 'OYO'), ('plateau', 'PLATEAU'), ('rivers', 'RIVERS'), ('sokoto', 'SOKOTO'), ('taraba', 'TARABA'), ('yobe', 'YOBE'), ('zamfara', 'ZAMFARA'), ('abuja', 'ABUJA')], max_length=11)),
            ],
        ),
    ]
