# Generated by Django 6.1.1 on 2026-10-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='location',
            new_name='address',
        ),
    ]
