# Generated by Django 6.1.1 on 2026-10-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_departmentstaff_department'),
        ('enterprises', '0002_rename_location_enterprise_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='departments.department'),
            preserve_default=False,
        ),
    ]
