# Generated by Django 6.1.1 on 2026-10-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_enterprise_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
