# Generated by Django 6.1.1 on 2026-10-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SUPERVISOR', 'Supervisor'), ('STAFF', 'Department Staff')], max_length=20),
        ),
    ]
